name: complexipy
description: Calculate the cognitive complexity of Python files, written in Rust.
inputs:
  paths:
    description: Paths to analyze. Can be local paths or a git repository URL.
    required: true
    default: ${{ github.workspace }}
  output_csv:
    description: Generate results in a CSV file.
    required: false
    default: 'false'
  output_json:
    description: Generate results in a JSON file.
    required: false
    default: 'false'
  ignore_complexity:
    description: Ignore complexity threshold and show all functions. By default, complexipy will fail if a function exceeds a certain complexity.
    required: false
    default: 'false'
  details:
    description: 'Output detail level (`low` or `normal`).'
    required: false
    default: "normal"
  quiet:
    description: Suppress console output.
    required: false
    default: 'false'
  sort:
    description: 'Sort results by complexity (`asc`, `desc`, or `name`).'
    required: false
    default: "asc"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.paths }}
    - ${{ inputs.ignore_complexity }}
    - ${{ inputs.output_csv }}
    - ${{ inputs.output_json }}
    - ${{ inputs.details }}
    - ${{ inputs.quiet }}
    - ${{ inputs.sort }}
branding:
  icon: "check-circle"
  color: "purple"